### ISSUE TITLE
拆分 docker_publish.yml 為多個獨立的工作流程檔案以優化 CI/CD 管道

### ISSUE THREAD

**Issue by bot0419** [jim60105/docker-whisperX#83]
# 專案目標

將現有的單一 `docker_publish.yml` 工作流程檔案拆分成 5 個獨立的 YAML 檔案，以提高 CI/CD 管道的可維護性、並行處理效率和故障隔離能力。目前的工作流程包含 175+ 個 Docker 映像（每個 10GB）的建構，拆分後將能更好地管理建構資源和錯誤處理。

## 背景資訊

當前的 `docker_publish.yml` 包含以下主要工作階段：
1. `docker-ubi-no_model` - 建構 UBI 基底映像（無模型）
2. `docker-no_model` - 建構標準基底映像（無模型）
3. `docker-cache` - 建構模型快取映像（6 種模型的矩陣建構）
4. `docker-distil-large-v3-en` - 建構 distil-large-v3 英文專用映像
5. `docker` - 建構完整的映像矩陣（37 種語言 × 5 種模型 = 185 個建構任務）
6. `test-large-v3-zh` - 測試中文映像功能

### 步驟 1：建立工作流程檔案結構

建立以下 5 個新的工作流程檔案：

```
.github/workflows/
├── 01-build-base-images.yml     # ubi-no_model 和 no_model
├── 02-build-model-cache.yml     # docker-cache 矩陣建構
├── 03-build-distil-en.yml       # docker-distil-large-v3-en
├── 04-build-matrix-images.yml   # docker 矩陣建構和測試
└── docker_publish.yml           # 保留作為觸發入口點
```

### 步驟 2：設計工作流程鏈結機制

使用 `workflow_run` 事件來建立工作流程間的相依性鏈：

```yaml
on:
  workflow_run:
    workflows: ["Previous Workflow Name"]
    types: [completed]
```

#### 3.1 `01-build-base-images.yml`
**目的：** 建構兩個基底映像（ubi-no_model 和 no_model）
**觸發條件：** `workflow_run` 從 `docker_publish.yml`
**包含工作：**
- `docker-ubi-no_model` job
- `docker-no_model` job
**輸出：** 基底映像的 digest 資訊，供後續工作流程使用

```yaml
# Code example for workflow output
outputs:
  no_model_digest:
    description: "Digest of the no_model image"
    value: ${{ jobs.docker-no_model.outputs.digest }}
  ubi_no_model_digest:
    description: "Digest of the ubi-no_model image"
    value: ${{ jobs.docker-ubi-no_model.outputs.digest }}
```

#### 3.2 `02-build-model-cache.yml`
**目的：** 建構 6 種 Whisper 模型的快取映像
**觸發條件：** `workflow_run` 從 `01-build-base-images.yml` 且狀態為 `completed`
**包含工作：**
- `docker-cache` job（包含完整的矩陣建構策略）
**相依性：** 需要從前一個工作流程獲取 `no_model_digest`

```yaml
# Code example for accessing previous workflow outputs
env:
  NO_MODEL_DIGEST: ${{ github.event.workflow_run.outputs.no_model_digest }}
```

#### 3.3 `03-build-distil-en.yml`
**目的：** 建構 distil-large-v3-en 專用映像
**觸發條件：** `workflow_run` 從 `02-build-model-cache.yml` 且狀態為 `completed`
**包含工作：**
- `docker-distil-large-v3-en` job
**特色：** 獨立的工作流程，專門處理英文優化的 distil 模型

#### 3.4 `04-build-matrix-images.yml`
**目的：** 建構完整的映像矩陣並執行測試
**觸發條件：** `workflow_run` 從 `02-build-model-cache.yml` 且狀態為 `completed`
**包含工作：**
- `docker` job（37 種語言 × 5 種模型的矩陣建構）
- `test-large-v3-zh` job（測試中文映像）
**並行處理：** 與 `03-build-distil-en.yml` 並行執行

#### 3.5 `docker_publish.yml`（重構後）
**目的：** 作為主要觸發點和狀態監控
**功能：**
- 保持原有的觸發條件（push, tags, workflow_dispatch）
- 觸發第一個工作流程 `01-build-base-images.yml`
- 可選：提供整體建構狀態的彙總資訊

#### 4.1 基底映像 Digest 傳遞
由於後續工作流程需要使用特定的基底映像 digest，需要建立機制來傳遞這些資訊：

```yaml
# In build args example
build-args: |
  NO_MODEL_STAGE=ghcr.io/jim60105/whisperx:no_model@${{ needs.get-base-digest.outputs.digest }}
```

#### 4.2 共用的 Reusable Actions
確保所有工作流程都能存取現有的 `docker-reused-steps` action：

```yaml
# Consistent usage across workflows
- name: Setup docker
  id: setup
  uses: ./.github/workflows/docker-reused-steps
  with:
    tag: ${{ matrix.model }}-${{ matrix.lang }}
```

#### 5.1 條件執行
每個工作流程都應檢查前一個工作流程的執行狀態：

```yaml
# Code example for conditional execution
if: ${{ github.event.workflow_run.conclusion == 'success' }}
```

#### 5.2 失敗處理策略
- 設定 `fail-fast: false` 適當的矩陣建構
- 實作重試機制適用於網路相關的失敗
- 建立通知機制來報告建構失敗

#### 6.1 快取策略維護
確保拆分後的工作流程仍能有效利用 Docker layer 快取：

```yaml
# Maintain cache consistency across workflows
cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/whisperx:cache
cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/whisperx:cache,mode=max
```

#### 6.2 並行處理最佳化
- `03-build-distil-en.yml` 和 `04-build-matrix-images.yml` 可以並行執行
- 在 `04-build-matrix-images.yml` 中維持現有的矩陣並行處理策略

#### 7.1 工作流程測試
建立測試分支來驗證新的工作流程鏈：
- 測試各工作流程間的相依性觸發
- 驗證資料傳遞的正確性
- 確認錯誤處理機制的有效性

#### 7.2 建構時間分析
比較拆分前後的總建構時間：
- 量測各階段的執行時間
- 評估並行處理的效益
- 優化瓶頸階段

#### 8.1 README.md 更新
更新專案說明，解釋新的多階段建構流程：

```markdown
# Build Process
The Docker images are built through a multi-stage CI/CD pipeline:
1. Base Images (ubi-no_model, no_model)
2. Model Cache (6 whisper models)
3. Specialized Images (distil-large-v3-en)
4. Matrix Images (185 combinations) with Testing
```

#### 8.2 工作流程文件
建立新文件說明各工作流程的用途和相依性關係。

### 1. 改善的可維護性
- **模組化設計：** 每個工作流程專注於特定的建構階段
- **獨立偵錯：** 可以單獨測試和修復特定階段的問題
- **程式碼重用：** 共用的邏輯可以更容易地重構和優化

### 2. 增強的並行處理
- **階段性並行：** distil-en 和矩陣建構可以並行執行
- **資源最佳化：** 避免在單一工作流程中過度使用 GitHub runner 資源
- **故障隔離：** 一個階段的失敗不會立即影響其他獨立階段

### 3. 改善的監控和除錯
- **精細狀態追蹤：** 可以清楚看到每個建構階段的狀態
- **選擇性重跑：** 可以只重新執行失敗的特定階段
- **日誌分離：** 更容易找到和分析特定階段的建構日誌

### 4. 更好的 CI/CD 管理
- **漸進式部署：** 可以逐步測試和部署建構流程的改變
- **版本控制：** 每個工作流程可以獨立進行版本控制和回滾
- **策略彈性：** 可以為不同的建構階段採用不同的執行策略

### 1. 相依性複雜度
**風險：** 工作流程間的相依性可能導致調試困難
**緩解：** 
- 建立清晰的相依性文件
- 實作完整的日誌記錄
- 建立工作流程狀態監控儀表板

### 2. 資料傳遞失敗
**風險：** 工作流程間的資料傳遞可能失敗
**緩解：**
- 實作資料驗證機制
- 建立備用的資料獲取方法
- 增加重試邏輯

### 3. 整體建構時間增加
**風險：** 工作流程鏈可能增加總建構時間
**緩解：**
- 最佳化並行執行策略
- 監控和調整各階段的執行時間
- 實作智慧快取策略

### 功能性要求
1. ✅ 所有 5 個新工作流程都能成功執行
2. ✅ 工作流程間的相依性觸發正常運作
3. ✅ 產生的 Docker 映像與原始工作流程完全相同
4. ✅ 測試工作能正常執行並通過

### 效能要求
1. ✅ 總建構時間不超過原始工作流程的 110%
2. ✅ 並行處理效率得到改善
3. ✅ 快取命中率維持在原始水準

### 可維護性要求
1. ✅ 每個工作流程都有清楚的文件說明
2. ✅ 錯誤處理機制完善
3. ✅ 監控和日誌記錄完整

### 階段 1：設計和準備（1-2 天）
- 詳細設計各工作流程檔案的結構
- 準備測試環境和分支

### 階段 2：實作基礎工作流程（2-3 天）
- 建立 `01-build-base-images.yml`
- 建立 `02-build-model-cache.yml`
- 測試基礎相依性鏈

### 階段 3：實作進階工作流程（2-3 天）
- 建立 `03-build-distil-en.yml`
- 建立 `04-build-matrix-images.yml`
- 實作並行處理邏輯

### 階段 4：整合和測試（2-3 天）
- 重構 `docker_publish.yml`
- 執行完整的整合測試
- 效能調優和問題修復

### 階段 5：文件和部署（1 天）
- 更新文件
- 部署到正式環境
- 監控初期執行狀況

### 1. 監控計畫
- 建立 GitHub Actions 執行狀況的監控
- 追蹤建構時間和成功率指標
- 定期檢視工作流程效能

### 2. 優化機會
- 根據實際使用狀況調整並行處理策略
- 持續優化 Docker layer 快取策略
- 評估是否需要進一步拆分大型矩陣建構

### 3. 擴展計畫
- 評估是否可以應用類似的拆分策略到其他工作流程
- 考慮實作更進階的條件執行邏輯
- 探索使用 GitHub Actions 的新功能來進一步優化

這個拆分計畫將顯著改善 docker-whisperX 專案的 CI/CD 管道可維護性，並為未來的擴展提供更好的基礎架構。透過模組化的設計，我們能夠更有效地管理複雜的 Docker 建構流程，同時保持高效的並行處理能力。
